nginx:
    image: tutum/nginx
    ports:
        - "80:80"
    links:
        - phpfpm
    volumes:
        - ./nginx/default:/etc/nginx/sites-available/default
        - ./nginx/default:/etc/nginx/sites-enabled/default
        - C:\DEVLAB\CURSOS_UDEMY\CURSO_UDEMY_WEB:/usr/share/nginx/html
        # - ./logs/nginx-error.log:/var/log/nginx/error.log
        # - ./logs/nginx-access.log:/var/log/nginx/access.log

phpfpm:
    image: php:fpm
    ports:
        - "9000:9000"
    volumes:
        - C:\DEVLAB\CURSOS_UDEMY\CURSO_UDEMY_WEB:/usr/share/nginx/html
        
mysql:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: appsalon
    MYSQL_USER: chan
    MYSQL_PASSWORD: 961421180     
  ports:
    - "3306:3306" 
  volumes:
    - ./mysql:/var/lib/mysql  
# phpmyadmin:
#   image: phpmyadmin/phpmyadmin
#   restart: always
#   links:
#     - mysql
#   ports:
#     - 8183:80
#   environment:
#     PMA_USER: root
#     PMA_PASSWORD: admin
#     PMA_ARBITRARY: 1
